import { jsPDF } from 'jspdf';
import { Term } from '@shared/schema';
import Papa from 'papaparse';

/**
 * Export terms to PDF
 */
export const exportToPDF = (terms: Term[], username: string) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(18);
  doc.setTextColor(15, 52, 96); // Primary color
  doc.text('LawLexicon - Favorite Terms', 20, 20);
  
  // Add user info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Generated for: ${username}`, 20, 30);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 36);
  
  // Add terms
  doc.setFontSize(14);
  doc.setTextColor(15, 52, 96); // Primary color
  
  let yPosition = 50;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  terms.forEach((term, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Add term title
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(15, 52, 96); // Primary color
    doc.text(`${index + 1}. ${term.term}`, margin, yPosition);
    yPosition += 8;
    
    // Add origin if exists
    if (term.origin) {
      doc.setFontSize(10);
      doc.setFont(undefined, 'italic');
      doc.setTextColor(100, 100, 100);
      doc.text(`[${term.origin}]`, margin, yPosition);
      yPosition += 6;
    }
    
    // Add definition
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(0, 0, 0);
    
    const definitionLines = doc.splitTextToSize(term.definition, contentWidth);
    doc.text(definitionLines, margin, yPosition);
    yPosition += (definitionLines.length * 5) + 4;
    
    // Add example if exists
    if (term.example) {
      doc.setFontSize(10);
      doc.setFont(undefined, 'italic');
      doc.setTextColor(100, 100, 100);
      
      const exampleLines = doc.splitTextToSize(`Example: "${term.example}"`, contentWidth);
      doc.text(exampleLines, margin, yPosition);
      yPosition += (exampleLines.length * 5) + 10;
    } else {
      yPosition += 10;
    }
  });
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Generated by LawLexicon | Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' });
  }
  
  // Save the PDF
  doc.save('lawlexicon-favorites.pdf');
};

/**
 * Export terms to CSV
 */
export const exportToCSV = (terms: Term[]) => {
  // Prepare the data for CSV export
  const data = terms.map(term => ({
    Term: term.term,
    Origin: term.origin || '',
    Pronunciation: term.pronunciation || '',
    Definition: term.definition,
    Example: term.example || '',
    Category: term.category || '',
  }));
  
  // Convert to CSV using Papa Parse
  const csv = Papa.unparse(data);
  
  // Create a blob and download
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', 'lawlexicon-favorites.csv');
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
